### ISSUE TITLE
Size of #FB Logo in header

### ISSUE THREAD

**Issue by asteyaert19** [barnardos/FB-2019#2]
**Need**

For the #FutureBarnardos logo that sits in the header to adhere to current Future Barnardos guidelines.

**Description**

The Future Barnardos style guidelines state that logo has a certain clearance area around it. This is equal to the height and width of the '#'. I have added an attachment that shows this clearance area.

At the moment, the #FutureBarnardos logo in the header is too big. There's not enough clearance space around it. Please use the guidelines to make the spacing correct.

**Affected pages**

All pages

**Acceptance criteria**

When the logo has enough clearance space around it, equal to the width and height of the '#'.

<img width="903" alt="#FB Logo guidelines" src="https://user-images.githubusercontent.com/58941226/70912657-54a4bc00-200c-11ea-8ed1-df002b568b7c.png">
<img width="465" alt="Header Logo" src="https://user-images.githubusercontent.com/58941226/70912684-638b6e80-200c-11ea-8c51-7b898878427a.png">

**Comment by olimj** [comment]
@asteyaert19 Not totally sure this guidance is applicable to digital so much? It also isn't practical for headers on smaller screens where real estate is limited? On larger screens we're not that far off the guidelines anyway?

**Comment by olimj** [comment]
Sorry, I don't want to be dismissive, just want to make we're all on the same page. Shall we do a quick call?
