### ISSUE TITLE
Styling title blocks

### ISSUE THREAD

**Issue by asteyaert19** [barnardos/FB-2019#3]
**Need**

For the title blocks on each page to be styled in line with #FutureBarnardos guidelines.

**Description**

The title blocks containing the title on each page currently have a solid magenta background colour. There is quite a lot of magenta across the site. Having magenta on white on both the header and title section can be hard to read. 

Can we try and work on how this can be styled to be more legible for users. 

Two options: 
1. Make the title copy magenta on a white background.
2. Make the title copy colours from the #FB guidelines on a white background. (eg. teal, orange, purple)

Please refer to the latest pdf where we use other colours in the #FB colour palette to highlight different areas. 

**Affected pages**

All pages

**Acceptance criteria**

A style for the titles that sits within #FB guidelines, and is more legible for a user.

<img width="1224" alt="Screen Shot 2019-12-16 at 14 47 14" src="https://user-images.githubusercontent.com/58941226/70916117-0b0b9f80-2013-11ea-8a40-54b572c78fc0.png">
<img width="1223" alt="Screen Shot 2019-12-16 at 14 47 18" src="https://user-images.githubusercontent.com/58941226/70916118-0b0b9f80-2013-11ea-83ae-cc1a399eea06.png">
<img width="1221" alt="Screen Shot 2019-12-16 at 14 47 22" src="https://user-images.githubusercontent.com/58941226/70916119-0b0b9f80-2013-11ea-9db9-1c1b0d9e2031.png">
<img width="1222" alt="Screen Shot 2019-12-16 at 14 47 27" src="https://user-images.githubusercontent.com/58941226/70916122-0ba43600-2013-11ea-9135-6742164036d5.png">
<img width="1219" alt="Screen Shot 2019-12-16 at 14 47 36" src="https://user-images.githubusercontent.com/58941226/70916123-0ba43600-2013-11ea-8a53-1397e8be5d18.png">

**Comment by olimj** [comment]
@asteyaert19 We're using the design system convention here for these hero titles: https://design-system.barnardos.org.uk/components/content/#heroes

See the solid colour background. If anything needs to change then perhaps it would be the solid pink on the header instead?

**Comment by olimj** [comment]
@claredowson title component can be used instead of the hero and we can play around with the use of colour on it: https://design-system.barnardos.org.uk/components/content/#title
